// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzZ-2OmqXgEkdIoBSLUi75j8gJTTOqVE',
    appId: '1:736051025902:web:7aae375a89bbf32d25e0ff',
    messagingSenderId: '736051025902',
    projectId: 'codexntpu',
    authDomain: 'codexntpu.firebaseapp.com',
    storageBucket: 'codexntpu.appspot.com',
    measurementId: 'G-BDPQ5H29FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1DTh3R7bKHnA0jt70sP16l6Kr3fwS634',
    appId: '1:736051025902:android:9e5562cb92fb7e3525e0ff',
    messagingSenderId: '736051025902',
    projectId: 'codexntpu',
    storageBucket: 'codexntpu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHIpw5Inf7FLFX0_jH7-5j_xPSdHjbtqE',
    appId: '1:736051025902:ios:aca49f204949000625e0ff',
    messagingSenderId: '736051025902',
    projectId: 'codexntpu',
    storageBucket: 'codexntpu.appspot.com',
    iosBundleId: 'com.example.interviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlgYZM3HALdCpKLosw9m2ekMA6Nl1SJ40',
    appId: '1:980467432782:ios:7a99ca1e2549461450321f',
    messagingSenderId: '980467432782',
    projectId: 'codexntpu-31432',
    storageBucket: 'codexntpu-31432.appspot.com',
    iosBundleId: 'com.example.interviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOIgeA7WVKWQK3F0KL3QAd-7xZCg2G4BQ',
    appId: '1:980467432782:web:8f0500c337848aeb50321f',
    messagingSenderId: '980467432782',
    projectId: 'codexntpu-31432',
    authDomain: 'codexntpu-31432.firebaseapp.com',
    storageBucket: 'codexntpu-31432.appspot.com',
    measurementId: 'G-XLXCK6TB9C',
  );
}