// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2G5f7Cv5OQlnTHcGHMfLtOzuPH_00V3c',
    appId: '1:86201319521:web:41caf97d01e3e27c77ea20',
    messagingSenderId: '86201319521',
    projectId: 'codexntpu-41ef6',
    authDomain: 'codexntpu-41ef6.firebaseapp.com',
    storageBucket: 'codexntpu-41ef6.appspot.com',
    measurementId: 'G-MGK1S2SND5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NmZFkM7N9ys3mASc0xT8wbfK3gGxolc',
    appId: '1:86201319521:android:48f2a47f6e371edf77ea20',
    messagingSenderId: '86201319521',
    projectId: 'codexntpu-41ef6',
    storageBucket: 'codexntpu-41ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWsGkSpKU8V_m9EUJGCS6Lu5XZOfwNls',
    appId: '1:86201319521:ios:88e50198969a54b777ea20',
    messagingSenderId: '86201319521',
    projectId: 'codexntpu-41ef6',
    storageBucket: 'codexntpu-41ef6.appspot.com',
    iosBundleId: 'com.example.interviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWsGkSpKU8V_m9EUJGCS6Lu5XZOfwNls',
    appId: '1:86201319521:ios:88e50198969a54b777ea20',
    messagingSenderId: '86201319521',
    projectId: 'codexntpu-41ef6',
    storageBucket: 'codexntpu-41ef6.appspot.com',
    iosBundleId: 'com.example.interviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2G5f7Cv5OQlnTHcGHMfLtOzuPH_00V3c',
    appId: '1:86201319521:web:b3fa19e5e4de8e5477ea20',
    messagingSenderId: '86201319521',
    projectId: 'codexntpu-41ef6',
    authDomain: 'codexntpu-41ef6.firebaseapp.com',
    storageBucket: 'codexntpu-41ef6.appspot.com',
    measurementId: 'G-2QG62YSLQL',
  );
}
